version: "3"
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "14269"
      - "5778:5778"
      - "14268:14268"
      - "14267"
      - "16686:16686"
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
  consul:
    image: consul:latest
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redis_dev_data:/data
  postgres:
    image: postgres:11.7
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password0000
      POSTGRES_DB: citicoins
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data/
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pbadmin@citicoins.io
      PGADMIN_DEFAULT_PASSWORD: pass0000
    volumes:
      - pbadmin_dev_data:/root/.pgadmin
    ports:
      - "5001:80"
    restart: unless-stopped
volumes:
  redis_dev_data:
    external: false
  postgres_dev_data:
    external: false
  pbadmin_dev_data:
    external: false
